### ISSUE TITLE
I2C multiplexer problem

### ISSUE THREAD

**Issue by zsole2** [kizniche/mycodo_python#18]
Kyle,

I finally got an I2C multiplexer, although it is not the Adafruit version, but a replica from Ebay. It is detected by the test script.
However, when I connect my pressure sensor, activate it, there is no data recorded. The pressure sensor works without the multiplexer, and  the pressure sensor test script also works, both directly, and through the multiplexer. 
The daemon log shows WARNING - [Sensor VzBv9bdp] Could not set channel with multiplexer at address 0x70. Error: Multiplexer Fail: 'TCA9548A' object has no attribute 'sensor_id'
What is interesting to me that i2cdetect shows both addresses (70 for the multiplexer and 77 for the BMP). Shouldn't it only detect the multiplexer?

**Comment by kizniche** [comment]
Ah! That appears to be an error with Mucodo and not your setup. I will have to push a fox later. I'm currently out of town at a science conference (white-nose syndrome workshop) and might not be able to get to it until this weekend when I return home. If you would like to allow me to connect to your pi to speed up finding a solution (as I have my multiplexer connected to my development pi at home, but no sensor connected), I could potentially connect this evening to try and figure out a solution and push it. Otherwise, I'll make it a priority when I get home this weekend.

**Comment by zsole2** [comment]
Thanks for the quick reply. I'm in no rush, just playing around. In the meantime, I will try to check out my other new toy, an LCD panel. Have fun at the conference!

**Comment by kizniche** [comment]
Should be fixed in 76fc396

**Comment by zsole2** [comment]
Thanks, I confirm it works
